export enum ActionType {
  SWAL_LOADING = "SWAL_LOADING",
  USER_LOGIN = "USER_LOGIN",
  USER_REGISTER = "USER_REGISTER",
  USER_LOGOUT = "USER_LOGOUT",
  USER_DATA = "USER_DATA",
  USER_ROLE = "USER_ROLE",
}
